name: data_care_app
description: Android application scaffold for Data Care.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  connectivity_plus: ^7.0.0
  # animated_bottom_navigation_bar: ^1.4.0
  google_nav_bar: ^5.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
